### ISSUE TITLE
Audio behaves oddly.

### ISSUE THREAD

**Issue by anti-beep** [fapnip/openeos#2]
**Describe the bug**
I have an audio tag, with audio in it:

![image](https://user-images.githubusercontent.com/67585977/103932169-b9541c80-5121-11eb-8f9c-9d23fa6cc5d2.png)

This audio tag is placed on the second page in the tease. For development reasons, my first page is a prompt, and an eval to go to the page with an ID typed into the prompt. (Meaning I am not actively preloading any pages)

When I arrive on the first page, no audio is heard. But if I wait an amount of time corresponding to the length of the audio file, the audio file will play, infinitely looping. Oddly enough, if I set it to not loop, the audio will never be heard (not even on the page where the audio element is found). If i set any amount of loops (2, 3 .. ∞) the audio will loop forever, even on pages where it is not supposed to.

*Example:* I have a 15 second audio set to loop (amount of loops is irrelevant), starting on page 2. ``Continue across pages`` is disabled. I sit on page 1 for 15 seconds, in silence. The audio plays, looping infinitely. I can not stop this audio by any means within the tease.

If I have multiple audio elements on a loop (located anywhere), they will all start playing after the amount of time.

**Further**, if I start an audio with ``new Sound()`` instead of with an element, it will not start playing untill the sound instance has actually been created. However, if I stop the sound it will continue playing after 1 loop of silence.

*Example:* I use ``new Sound()`` to start an audio. The audio file is 15 seconds and looping, I stop it with both ``.stop()`` and/or ``.destroy()`` after 5 seconds of playing. After 10 seconds of silence, the audio will play again, looping forever. Going to a new page before or after the bug happens, has no effect on it.

I tried forking the project but couldn't actually do any debugging because of a failed cors request to Heroku.

I am pretty sure this happened within the last couple of days, I suspect it is caused by b40847c.

**Comment by fapnip** [comment]
I'm working on refactoring the Sound/Audio action.   Unfortunately, Howler has some issues/limitation, and my current hacks to work-around them aren't working very well.

For CORS on local development, see:
https://github.com/fapnip/openeos/blob/master/.env.development

**Comment by fapnip** [comment]
Put up a temporary change that will hopefully get it working, at the cost of all audio files being fully downloaded at start of tease instead of just pre-buffered.

Still working on refactoring audio to a different library, but let me know if this helps for now.

**Comment by anti-beep** [comment]
I can confirm that the bug is no longer present for my tease.

Thanks a lot for your work!

**Comment by fapnip** [comment]
Good to hear, and thanks for the report!   I'll close this issue for now.
